services:
  kilasonia:
    build: .
    container_name: kilasonia-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot-client
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      /bin/sh -c "
        while :; do
          certbot renew --quiet --post-hook 'docker exec kilasonia-app nginx -s reload';
          sleep 12h & wait $$!;
        done
      "

volumes:
  certbot-etc: