# nginx.conf

# HTTP сервер для перенаправления на HTTPS
server {
    listen 80;
    server_name kilasonia.tech; # Замени на свой домен

    # Специальный location для верификации Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Все остальные запросы на HTTP перенаправляем на HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS сервер с SSL
server {
    listen 443 ssl;
    server_name kilasonia.tech; # Замени на свой домен

    # Пути к сертификатам (будут смонтированы из volumes)
    ssl_certificate /etc/letsencrypt/live/kilasonia.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kilasonia.tech/privkey.pem;
    
    # Рекомендуемые настройки SSL (можно найти в документации Certbot)
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Корень с твоим React-приложением
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}